name: uber_appclone
description: Clone do App Uber

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+10
  geolocator: ^5.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/login-banner.png
    - assets/login_image.png
    - assets/login-img.png
    - assets/br.png
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/money_logo.png
    - assets/reward_logo.png
    - assets/uber_logo.jpeg
    - assets/voucher_logo.png

