name: uber_appclone
description: Clone do App Uber

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^5.1.5
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+10
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  google_sign_in: ^4.0.7
  rxdart: ^0.22.6
  cloud_firestore: ^0.12.9+5
  shared_preferences: ^0.5.3+4
  firebase_storage: ^3.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/login-banner.png
    - assets/login_image.png
    - assets/login-img.png
    - assets/br.png
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/money_logo.png
    - assets/reward_logo.png
    - assets/uber_logo.jpeg
    - assets/voucher_logo.png

